[project]
name = "silksong-gpt-translate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "crypto>=1.4.1",
    "pycryptodome>=3.20.0",
    "unitypy>=1.23.0",
]
